### ISSUE TITLE
PHPStan "Class not found" errors during check for deprecated code on ProboCI

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az-quickstart-scaffolding#11]
**Describe the bug**
The probo check for Deprecated Code has the same error twice

```
Internal error: Class                                                                         
'Drupal\TestTools\PhpUnitCompatibility\RunnerVersion' not found                               
Run PHPStan with --debug option and post the stack trace to:                                  
https://github.com/phpstan/phpstan/issues/new  
```

**To Reproduce**

1. Submit a pull request
2. Look at the "checks" section
3. View details on Deprecated Code

**Expected behavior**
Check fo Deprecated Code only fails if the pull request introduces non-standard code

**Screenshots**
![image](https://user-images.githubusercontent.com/3914737/74559136-ee132000-4f20-11ea-9aeb-d7a22fba3de0.png)

**Comment by joeparsons** [comment]
These PHPStan "Class not found" errors don't seem to occur when using the latest drupal-check release locally so perhaps we should see if we can apply the fix for the drupal-check TTY issue from [this PR](https://github.com/mglaman/drupal-check/pull/135) as a patch in our az-quickstart-scaffolding composer.json config until a new drupal-check release is available.
